# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/webchecker
    username: webchecker
    password: webchecker
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Mail Configuration (for notifications)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Supabase Configuration
supabase:
  jwt:
    secret: ${SUPABASE_JWT_SECRET:your-supabase-jwt-secret}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    com.webchecker.backend: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
